### ISSUE TITLE
fetching chart JSON from "CDN" returns 404 for v0.x

### ISSUE THREAD

**Issue by tomwayson** [Esri/cedar#458] opened 2019-01-08 17:18 UTC
This affects anyone using v0.x ~~installed via `npm i` (i.e. not using `<script>` tags)~~ in node.

The issue is that the `baseUrl` [defaults to a folder on github.io](https://github.com/Esri/cedar/blob/671cce10b34a246ce7bb99a3e4d61586c2c4d84d/src/cedar.js#L10-L28) which no longer exists after I recently deployed the v1 docs via gh-pages. I didn't realize that the code was dependent on the location where the docs are deployed. Really it should point to the actual CDN (https://unpkg.com/arcgis-cedar@0.9.2/dist).

We should:
- [x] add a step to the v1.x docs deploy process that pushes the v0.9.2 `/charts` folder to the above location
- [x] update the above code to point to unpkg instead of the docs site and
- [x] cut a v0.9.3 release

Until we get to those fixes, affected users can pass `baseUrl: 'https://unpkg.com/arcgis-cedar@0.9.2/dist` (and replace `@0.9.2` w/ whatever version they are using) in the options to the cedar constructor to avoid this error.

**Comment by tomwayson** [comment] 2019-01-08 17:22
Discovered by @christianhoward

**Comment by jgravois** [comment] 2019-01-10 01:13
i'm not able to reproduce the error as described (more info in https://github.com/Esri/cedar/pull/459).

**Comment by jgravois** [comment] 2019-01-10 19:55
its just a guess, but _maybe_ they're seeing something different because they're running an older version of webpack.
```
"webpack": "^2.2.1"
```

**Comment by tomwayson** [comment] 2019-01-10 21:10
@christianhoward 

> Charts are hidden behind a login. When a user does login, the app doesn’t show a chart.

Do you know if cedar is lazy loaded via a webpack chunk? That might explain how you could end up in the `else` side of this `if`:

https://github.com/Esri/cedar/blob/671cce10b34a246ce7bb99a3e4d61586c2c4d84d/src/cedar.js#L15-L16

**Comment by jasonhett** [comment] 2019-01-11 15:43
@tomwayson The script tag that loads our webpack bundle loads is via a callback once the dom is ready. The script tag is finished processing when the callback fires so `document.currentScript` will be undefined, causing it to end up in the `else`. 

```
<script>
  ...
  var dojoConfig = {  
    parseOnLoad: false,  
    async: true,  
    packages: [    
      { name: 'js', location: makePath(base, 'js') }  
    ],  
    deps: ['dojo/domReady!'],  
    callback: function () { require(['<%= htmlWebpackPlugin.files.js %>']); }   
  };  
</script>
```

**Comment by jgravois** [comment] 2019-01-12 00:58
thanks for confirming @jasonhett . #459 definitely _should_ resolve the problem then.

i'll tag another `0.x` release soon and push the files that 404ed up so we have all our bases covered.

**Comment by jgravois** [comment] 2019-01-14 17:06
[`v0.9.3`](https://github.com/Esri/cedar/releases/tag/v0.9.3) has been released with the fix. 

@christianhoward let me know if you have any further problems.

**Closed by jgravois** 2019-01-14 17:06 UTC
Labels: 0 - New, Medium, bug, v0x
