### ISSUE TITLE
Pie Chart Sample Doesn't Seem to Work

### ISSUE THREAD

**Issue by abakirov** [Esri/cedar#97] opened 2015-06-02 21:11 UTC
This sample doesn't seem to work with [latest cedar.js](https://github.com/Esri/cedar/blob/90381f3b4ab0442e6c3c0379b1c519019339c89f/src/cedar.js):
http://esri.github.io/cedar/examples/simple-pie.html

The chart does not render and shows this error in console:

![image](https://cloud.githubusercontent.com/assets/5304673/7947265/e44acf4a-0930-11e5-9b89-54cfa2fe9f95.png)

Have you guys seen anything like this before? I imagine I might be doing something wrong but not sure what exactly.

**Comment by tomwayson** [comment] 2015-06-03 00:26
I fixed this by reverting to an earlier version of vega (1.4.3). See:

https://github.com/Esri/cedar/blob/amd-examples/site/source/partials/header.hbs#L31

That comment should have said "pie chart" not "bar chart".

**Comment by tomwayson** [comment] 2015-06-04 14:40
@abakirov, can you confirm that this is fixed by #98 and close?

Also, I've opened #103 to track the issue of pie charts not working on v1.5.0.

**Comment by abakirov** [comment] 2015-06-04 15:51
Not sure how to confirm this. New samples seem a little broken to me (HTML portion is missing):
http://esri.github.io/cedar/examples/simple-pie.html

Should I point to an earlier version of Vega to test this? I'm just using this URL following your earlier samples:
```
<script src="http://trifacta.github.io/vega/vega.js"></script>
```
Do you have new fully-functional samples?

**Comment by tomwayson** [comment] 2015-06-04 16:38
First, I apologize b/c I had not pushed the changes in #98 to the docs site b/c my remote was still set to my own fork. I've now pushed to esri/gh-page and confirmed thatthe above page and all other pie chart pages are working:

http://esri.github.io/cedar/examples/multiple.html
http://esri.github.io/cedar/examples/bar-spec-inlined.html  (@ajturner looks like this one needs an updated title/url - you meant for this to be a pie chart now, right?)

Second, @ajturner removed the HTML portion from all the example pages, so they just show script now. You can view source for the HTML.

To test locally, you'll need this script tag for vega:

```html
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/vega/1.4.3/vega.min.js"></script>
```

**Comment by abakirov** [comment] 2015-06-04 18:23
Got it, thanks. Although it would be nice to have fully-functional sample HTML pages that people can simply copy and paste... otherwise it's pretty hard to get things to work. For example, I am now a little lost how I should be including Cedar and it's dependencies.

**Comment by tomwayson** [comment] 2015-06-04 18:58
Thanks.

An alternative to having the page header in every single sample would be to include it in the README, or to have a couple of quick start examples that include the header/footer. Thoughts @ajturner?

**Comment by ajturner** [comment] 2015-06-04 19:41
@abakirov I removed the examples for now because it made keeping them in sync w/ the code difficult. After this initial flurry I intend to do a revamp of the overall pages & docs.

The immediate sol'n @tomwayson points out is to update the README with the simple boilerplate getting started with the API for required `<script>` and minimally required API call. I can add that now.

**Comment by ajturner** [comment] 2015-06-04 19:57
@abakirov here you go https://github.com/Esri/cedar#getting-started

**Comment by abakirov** [comment] 2015-06-04 20:27
Cool, this helps! I was able to get it to work but I had to change the code (mappings were incorrect and query was missing). This code works:
```
  var chart = new Cedar({"specification":"http://esri.github.io/cedar/data/templates/pie.json"});
  //create the dataset w/ mappings
  var dataset = {
    "url":"http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Education_WebMercator/MapServer/5",
    "query": {
      "groupByFieldsForStatistics": "ZIP_CODE",
      "outStatistics": [{
        "statisticType": "sum", 
        "onStatisticField": "TOTAL_STUD", 
        "outStatisticFieldName": "TOTAL_STUD_SUM"
      }]
    },
    "mappings":{
      "label": {"field":"ZIP_CODE","label":"ZIP Code"},
      "y": {"field":"TOTAL_STUD_SUM","label":"Total Students"},
      "radius": 270
    }
  };
  chart.dataset = dataset;

  chart.show({
    elementId: "#chart",
    width: 600,
    height: 600
  }); 
```

**Comment by ajturner** [comment] 2015-06-04 21:06
Great. 

I mentioned the API changes coming - and there will be more. I'll make sure you're tagged and update the README if necessary.

**Comment by tomwayson** [comment] 2015-06-05 00:22
Closing in favor of #103

**Closed by tomwayson** 2015-06-05 00:22 UTC
