### ISSUE TITLE
Cedar v1-beta && Cedar v1 specification

### ISSUE THREAD

**Issue by benstoltz** [Esri/cedar#273] opened 2017-07-25 13:46 UTC
As things stand today:

- no top-level node (e.g. `charts`) in this version. that can be added later for trellis 
- `series:[{}]` objects can be complete, including `category, value`
- Additionally, any style elements (e.g. `category, value, alpha, color, size, ...`) can be a sibling of `series`. These will be merged into all series, effectively acting as defaults
- Multiple `datasets` will each have a `join`

## Compare v0 to v1

For the simplest chart, here is a comparison of v0 to v1:

### v0

```json
{
  "type": "scatter",
  "dataset": {
    "url": "https://services.arcgis.com/uDTUpUPbk8X8mXwl/arcgis/rest/services/Public_Schools_in_Onondaga_County/FeatureServer/0",
    "mappings": {
      "x": {"field": "Number_of","label": "Student Enrollment (2008)"},
      "y": {"field": "F_of_teach","label": "Fraction of Teachers"},
      "color": {"field": "Type","label": "Facility Type"}
    }
  }
}
```

### v1

```json
{
  "type":"scatter",
  "datasets":[{ 
    "url": "https://services.arcgis.com/uDTUpUPbk8X8mXwl/arcgis/rest/services/Public_Schools_in_Onondaga_County/FeatureServer/0"
  }],
  "series":[{
      "category": {"field":"Number_of","label":"Student Enrollment (2008)"},
      "value": {"field":"F_of_teach","label":"Fraction of Teachers"},
      "color":{"field":"Type","label":"Facility Type"}
    }]
  }
};
```

### Changelog

The changes are very concise:

- `dataset: {}` -> `datasets: [{}]`
- `mappings: {}` -> `series: [{}]` and moved to a root node
- `x` -> `category` & `y` -> `value`

Though extensive in what they enable...

### Tooltip

Tooltip needs to be per series. There can be a sensible default, but it needs to be configurable. Should this go into each `series:[{tooltip:{title: "", content: ""}}]` ? 

### Lines + Bar + Scatterplot

Similarly, chart _styles_ can be an option per series. in Amcharts these would clone a `graph` per style and mix into the chart template. 

For example:

```json
"category": {"field": "ZIP", "label": "Student Enrollment per Zip"}, 
"series": [
  { "style": "bar", "value": { "field": "BEDS_SUM", "label": "Number of Beds per Zip" }}
  { "style": "line", "value": { "field": "POPULATION_SUM", "label": "Population per Zip" }}
]
```

Though this conflates data + presentation, and perhaps even starts converging on Amcharts' own spec. 

## Some examples in progress 

```json
var studentsByTeacher = {
  "type":"scatter",
  "datasets":[{ "url":"https://services.arcgis.com/uDTUpUPbk8X8mXwl/arcgis/rest/services/Public_Schools_in_Onondaga_County/FeatureServer/0",}],
    "series":[{
      "category": {"field":"Number_of","label":"Student Enrollment (2008)"},
      "value": {"field":"F_of_teach","label":"Fraction of Teachers"},
      "color":{"field":"Type","label":"Facility Type"}
      }]
  }
};

var bedsByType = {
    "type": "bar",
    "datasets": [{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Hospitals/FeatureServer/0",
      "query": {
        "orderByFields": "POPULATION DESC",
        "groupByFieldsForStatistics": "TYPE",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "POPULATION",
            "outStatisticFieldName": "POPULATION_SUM"
          }
        ]
      }
    }],
    "series": [{
       "category": {"field": "TYPE", "label": "Type"},
       "value": { "field": "POPULATION_SUM", "label": "Number of Beds" }
     }],
  "overrides": {"categoryAxis": {"labelRotation": -45}
  }
};

var bedsByType = {
    "type": "bar",
    "datasets": [{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Hospitals/FeatureServer/0",
      "query": {
        "orderByFields": "POPULATION DESC",
        "groupByFieldsForStatistics": "TYPE",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "POPULATION",
            "outStatisticFieldName": "POPULATION_SUM"
          }
        ]
      }
    }],
    "series": [{
       "category": {"field": "TYPE", "label": "Type"},
       "value": { "field": "POPULATION_SUM", "label": "Number of Beds" }
     }],
  "overrides": {"categoryAxis": {"labelRotation": -45}
  }
};

var bedsByTypePerZip = {
    "type": "bar",
    "datasets": [{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Hospitals/FeatureServer/0",
      "query": {
        "where": "ZIP=20002",
        "orderByFields": "POPULATION_SUM_20002 DESC",
        "groupByFieldsForStatistics": "TYPE",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "POPULATION",
            "outStatisticFieldName": "POPULATION_SUM_20002"
          }
        ]
      },
      "join": {"field": "TYPE"}
    },{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Hospitals/FeatureServer/0",
      "query": {
        "where": "ZIP=90210",
        "orderByFields": "POPULATION_SUM_90210 DESC",
        "groupByFieldsForStatistics": "TYPE",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "POPULATION",
            "outStatisticFieldName": "POPULATION_SUM_90210"
          }
        ]
      },
      "join": {"field": "TYPE"}
    }],
    "compare": "grouped",
    "series": [
      {  "category": {"field": "TYPE", "label": "Type"}, 
          "value": { "field": "POPULATION_SUM_20002", "label": "Number of Beds in 20002" }},
      {   "category": {"field": "TYPE", "label": "Type"},
          "value": { "field": "POPULATION_SUM_90210", "label": "Number of Beds in 90210" }}
    ],
  "overrides": {"categoryAxis": {"labelRotation": -45}
  }
};

var bedsByStudentByPopulation = {
    "type": "scatter",
    "datasets": [{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Hospitals/FeatureServer/0",
      "query": {
        "orderByFields": "BEDS_SUM DESC",
        "groupByFieldsForStatistics": "ZIP",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "BEDS",
            "outStatisticFieldName": "BEDS_SUM"
          }
        ]
      }
    },{
      "url": "https://services2.arcgis.com/1cdV1mIckpAyI7Wo/arcgis/rest/services/Public_Schools/FeatureServer/0",
      "query": {
        "orderByFields": "ENROLLMENT_SUM DESC",
        "groupByFieldsForStatistics": "ZIP",
        "outStatistics": [
          {
            "statisticType": "sum",
            "onStatisticField": "ENROLLMENT",
            "outStatisticFieldName": "ENROLLMENT_SUM"
          },{
            "statisticType": "sum",
            "onStatisticField": "POPULATION",
            "outStatisticFieldName": "POPULATION_SUM"
          }
        ]
      }
    }],
    "series": [
      {  "category": {"field": "ENROLLMENT_SUM", "label": "Student Enrollment per Zip"}, 
          "value": { "field": "BEDS_SUM", "label": "Number of Beds per Zip" },
          "color": { "field": "POPULATION_SUM", "label": "Population per Zip" }
        }
    ],
  "overrides": {"categoryAxis": {"labelRotation": -45}
  }
};
```

**Comment by benstoltz** [comment] 2017-07-25 14:20
Some considerations @tomwayson @ajturner :

1) I'd like for us to define more clearly how we handle join vs merge. Currently internal behavior assumes it will be join,  however we've explicitly defined `join` as a property on a dataset. It might be better to specify `merge: true` to indicate we're going to be merging vs joining.

2) We need to decide on how we define functions that will run over data. There are three conditions, we run a function over each `attribute`, we run a function over each dataset, and we run a function over the entire data response. I don't think that we should define this on the cedar JSON specification itself, though it somewhat makes sense, because I think it opens the door to issues (someone trying to do a custom json chart card with a function in the json). However, if each of these options exist on `cedar()` then we need to define what they are called.

3) This probably isn't a `v1.0.0` issue, however we need to consider how we can indicate if a dataset is not an esri one, and how we deal with merging its data in with the rest of the data.... This could be solved by a dataset level transform function.

**Comment by ajturner** [comment] 2017-07-25 19:40
@benstoltz can you provide concrete examples of each case?

For #3 - we should allow passing in an array of data objects.

**Comment by tomwayson** [comment] 2017-07-25 20:26
w/r/t 1.

Based on the code @benstoltz showed me, I understand merge to effectively be "append the query response from the 2 datasets" and currently that behavior is envoked only when no datasets include a `join`. Unless I'm missing something, that logic seems sound to me, and doesn't feel like it needs a more explicit `merge: true`, though I think we'll need to have good documentation around `dataset.join`.

w/r/t 2.

> There are three conditions, we run a function over each attribute, we run a function over each dataset, and we run a function over the entire data response.

Is that a question, which of those we should support? Currently cedar runs a function over the entire data response. Is there a reason not to just do that? I see no reason to support the attribute/feature level transform functions - that can be achieved by running loops w/in the response/dataset level transform function.

> I don't think that we should define this on the cedar JSON specification itself

I agree. I think it should be set on the cedar chart instance. That will limit our flexibility in terms of what kind of charts can be saved/shared, but I agree that stabbing a function into what is otherwise a JSON serialization could cause problems downstream (i.e. in Hub page layouts).

w/r/t 3

> we should allow passing in an array of data objects

do you mean an array of _features_ (i.e. each has an `attributes` hash)? I think we should support features for v1, but not arrays of arbitrary objects. That can be added at a later release w/ some kind of flag (`format: 'arcgis' // default`), or a smart check for existence of `attributes`.

w/r/t 4

@benstoltz and I talked about this at length. My concern is that when we [ended our conversation and initial prototyping back in Feb](https://github.com/esridc/cedar-amcharts/pull/9#issuecomment-281883328) I was convinced that we didn't need an id to link datasets and series. Now, it's possible we didn't consider every scenario, and that we actually do need it under certain circumstances (say multiple datasets w/ multiple series). However, my mental model of how this work is that if you have multiple datasets is that they are joined (or merged?) into a single derived table, and that the series all refer to that derived table. Now, maybe the issue is that the derived table has things like generated field names (i.e. that end in `_0_1`) that won't exist at the time someone defines the series, and that's why we need to have a link back to the dataset to figure out what derived field we should be looking at. Either way, I'd say it's worth defining the exact conditions that require linking back to the dataset from the series and figuring out if there's a better way to solve that problem.

**Comment by tomwayson** [comment] 2017-08-08 17:03
Here's what's on my radar in terms of a punchlist for v1.0.0-beta:

- [ ] resolve api design questions by writing tests based on real world scenarios:
 - do we need to relate series to datasets (i.e `datasets[i].id` and `series[j].datasteId`)?
 - how should datasets indicate that they should be joined or appended ("merged") - `merged: true` vs. `join: 'join_field_name'`
 - [ ] final package names using scoped (@esri/*) packages
 - [ ] final package structure/dependencies 
  - move most (if not all) cedar-utils code into cedar
 - [ ] update build to output a single file (i.e. cedar-amcharts is bundled into cedar)
 - [ ] minimally viable docs/README
 - [ ] implement events (or is this a later beta?)
 - [ ] release/publish
  - [ ] additional tooling/scripts?
  - [ ] create v0 branch from current master
  - [ ] PR, merge, release, publish

I'll log add'l steps needed to get the new release into an ember app over in a new issue in ember-cli-cedar.

**Comment by tomwayson** [comment] 2017-08-10 18:57
this punchlist was getting unwieldy, and as always w/ these, I lost a bunch of comments/time when I tried updating the same time as @benstoltz so I made individual issues:

https://github.com/Esri/cedar/issues?q=is%3Aissue+is%3Aopen+label%3Av1-beta

**Closed** 2017-10-12 04:39 UTC
